### ISSUE TITLE
Download links

### ISSUE THREAD

**Issue by BinuxLiu** [mohwald/gandtr#2]
I can't open any of these download links.

**Comment by mohwald** [comment]
@BinuxLiu can you try to download one of the link with wget?

`wget http://ptak.felk.cvut.cz/personal/jenicto2/download/iccv23_gan/hedngan_embed_vgg16.pth`

If the weights do not download on your side, please put here the outputs of the command.

**Comment by BinuxLiu** [comment]
Thanks, this works.
