### ISSUE TITLE
Pre-trained models

### ISSUE THREAD

**Issue by fsbarros98** [mohwald/gandtr#5]
Hello there, I was wondering where did you get the pre-trained HED model from your config /mnt/fry2/landmarkdb/models/pytorch/weights/hed/sniklaus_github.pth, the one I get from the https://github.com/sniklaus/pytorch-hed has different model layer names so I can't load it directly on this code, did you train a model or simply changed the names of the layers from this one?

**Comment by mohwald** [comment]
Hi @fsbarros98 

Thanks for the question.

The weights are those from sniklaus, ~~but scaled down for [0, 1] pixel range~~.

You can now replace the path /mnt/fry2/... you are asking about with http://ptak.felk.cvut.cz/personal/jenicto2/download/iccv23_gan/hed_sniklaus_github.pth

Tommorow, I will fix the link in the yaml scenarios.

**Comment by mohwald** [comment]
I fixed now the weights loading so they are downloaded if needed: https://github.com/mohwald/gandtr/commit/bce54f6d96661e68afa45705e01b192a167b2b64

Layer names are different and correspond to [mdir/components/model/network/hed.py](https://github.com/mohwald/gandtr/blob/main/mdir/components/model/network/hed.py) Weights are the same like in [sniklaus/pytorch-hed](https://github.com/sniklaus/pytorch-hed).

@fsbarros98, please let me know if you can now load the weights now.

**Comment by fsbarros98** [comment]
Yes, thank you so much! :)
